/*
 * Debug parameters
 * 1: Print nova_info
 * 0: Block nova_info
 * Too many debug messages will lead to a crash!
 */

/* Mode */
#define MODE_USE_MEMCPY 0
#define MODE_USE_COOKIE 1
#define MODE_USE_GROUP 1
#define MODE_USE_DYN_THRES 0
#define MODE_KEEP_STAT 0
#define MODE_KEEP_STAT_VPMEM

#define MODE_FORE_ALLOC 0
#define MODE_FORE_PMEM 0
#define MODE_FORE_BAL 0
#define MODE_FORE_PREFETCH 1
#define MODE_FORE_LOG 0
#define MODE_BACK_MIG 1
#define MODE_REV_MIG 0
#define MODE_MIG_SELF 1

#define MODE_SR_FAULT 1
#define MODE_SR_WB 1

/* Configure */
#define BDEV_OPT_SIZE_BIT_INIT 6
#define VPMEM_MAX_PAGES_QTR_INIT 4096
#define MIGRATION_DOWN_PMEM_PERC_INIT 80
#define MIGRATION_IDEAL_PERC 70
#define MIGRATION_DOWN_BDEV_PERC 80
#define MIGRATION_FORCE_PERC 95
#define MIGRATION_MAX_PERC 99

/* Debug */
#define DEBUG_XFSTESTS 0

#define DEBUG_INIT 0
#define DEBUG_STARTUP_TEST 0

#define DEBUG_BDEV_RW 0
#define DEBUG_BFL_INFO 0
#define DEBUG_WRITE_ENTRY 0
#define DEBUG_KTHREAD 0

#define DEBUG_FORE_ALLOC 0
#define DEBUG_FORE_FILE 0

#define DEBUG_PROF_SYNC 0
#define DEBUG_PROF_SEQ 0
#define DEBUG_PROF_HOT 0

#define DEBUG_DO_MIGRATION 0
#define DEBUG_MIGRATION 0

#define DEBUG_MIGRATION_CHECK 0
#define DEBUG_MIGRATION_ALLOC 0
#define DEBUG_MIGRATION_COPY 0
#define DEBUG_MIGRATION_FREE 0
#define DEBUG_MIGRATION_CLONE 0

#define DEBUG_MIGRATION_ENTRY 0
#define DEBUG_MIGRATION_SPLIT 0
#define DEBUG_MIGRATION_MERGE 0
#define DEBUG_MIGRATION_SEM 0

#define DEBUG_GET_NVMM 0
#define DEBUG_MB_LOCK 0
#define DEBUG_BUFFERING 0
